const { Model, DataTypes } = require('sequelize');

const sequelize = require('../config/connection');

class ProductTag extends Model {}

ProductTag.init(
  {
    //All the tags for this through model are either pre-generated or generated by the 
    //relationships defined in index.js
    //product_id
    product_id: {
      type: DataTypes.INTEGER,
      references: {
        //should reference product model
        model: 'product',
        key: 'id',
        unique: false
      }
    },
    //tag_id
    tag_id: {
      type: DataTypes.INTEGER,
      references: {
        //should reference tag model
        model: 'tag',
        key: 'id',
        unique: false
      }
    }
  },
  {
    sequelize,
    timestamps: false,
    freezeTableName: true,
    underscored: true,
    modelName: 'product_tag',
  }
);

module.exports = ProductTag;
